---
title: "TJAL-Juris"
author: "Nathan Giachetta"
output: html_document
---

# TJAL: Consulta de Jurisprudencia

```{r}
library(rvest)
library(esaj)
library(dplyr)
library(stringr)
library(httr)
```

Objetivo: Obter os processos na segunda instância de classe "inquérito policial", na Unidade Federativa de Alagoas.

```{r}
# Download 
path <- "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/jurisprudencia/TJAL/data-raw_al/cjsg_AL/"
query_post <- list(conversationId = "", 
                       dados.buscaInteiroTeor = "",
                       dados.pesquisarComSinonimos = "S",
                       contadoragente = 0, 
                       contadorMaioragente = 0, 
                       contadorjuizProlator = 0, 
                       contadorMaiorjuizProlator = 0, 
                       classesTreeSelection.values = class_inq$id5, #Classe inquerito
                       assuntosTreeSelection.values = "", 
                       contadorcomarca = 0,
                       contadorMaiorcomarca = 0,
                       secoesTreeSelection.values = "", 
                       dados.dtJulgamentoInicio = "", # Quinta mudança
                       dados.dtJulgamentoFim = "", 
                       dados.dtRegistroInicio = "", 
                       dados.dtRegistroFim = "", 
                       dados.origensSelecionadas = "T", 
                       tipoDecisaoSelecionados = "A", 
                       dados.ordenarPor = "dtPublicacao")
dir.create(path, FALSE, TRUE)
path <- normalizePath(path)
file <- stringr::str_c(path, "/search.html")
httr::POST("https://www2.tjal.jus.br/cjsg/resultadoCompleta.do", # Primeira mudança
  body = query_post, httr::config(ssl_verifypeer = FALSE), 
  httr::write_disk(file, TRUE))

page <- "1"
file <- stringr::str_c(path, "/page", page, ".html")

query_get <- list(tipoDeDecisao = "A", pagina = page, 
            conversationId = "")    
httr::GET("https://www2.tjal.jus.br/cjsg/trocaDePagina.do",  #Segunda mudança
                query = query_get, httr::config(ssl_verifypeer = FALSE), 
                httr::write_disk(file, TRUE))

files <- dir(path, full.names = TRUE, pattern = "page")
```

#### Parseando os dados

```{r}
# Parseando o arquivo
node <- read_html(files, encoding = "UTF-8")

# infos
## id_lawsuit
id_lawsuit <- node %>% 
  rvest::html_nodes(xpath = '//*[@class="esajLinkLogin downloadEmenta"]') %>% html_text() %>% 
  str_trim() %>% tibble::tibble(id_lawsuit = .)

## id_decision
id_decision <- node %>% 
  rvest::html_nodes(xpath = '//*[@class="esajLinkLogin downloadEmenta"]') %>% html_attr("cdacordao") %>% 
  str_trim() %>% tibble::tibble(id_decision = .)

infos <- bind_cols(id_lawsuit, id_decision)

# id_page
## Precisa pegar apenas os elementos cujo os valores são impares
ementaClass <- node %>% 
  rvest::html_nodes(xpath = '//*[@class="ementaClass"]') %>% 
  html_text()
id_page <- ementaClass[c(1,3,5,7,9,11,13,15)] %>% str_replace_all("-", "") %>% str_trim() %>% 
   tibble::tibble(id_page = .)

# txt_summary
txt_summary <- node %>% html_nodes(".mensagemSemFormatacao") %>% html_text() %>% tibble::tibble(txt_summary = .)

# class_subject
class_base <- node %>% 
  html_nodes(xpath = '//*[@class="ementaClass2"]') %>%
  html_text() %>%
  stringr::str_split_fixed(':', 2) %>% 
  data.frame(stringsAsFactors = FALSE) %>%
  magrittr::set_names(c('key', 'val')) %>%
  dplyr::mutate_all(dplyr::funs(str_trim(.)))%>%
  dplyr::mutate(key = tolower(abjutils::rm_accent(key)),
                key = stringr::str_replace_all(key, ' +', '_'),
                key = stringr::str_replace_all(key, '[^a-z_]', ''),
                key = stringr::str_replace_all(key, '_d[eo]_', '_')) %>% 
  mutate(ementa = case_when(str_detect(key, "[E-e]menta") == T ~ "S",
                            T~"N")) 
i <- 1
class_base$group <- NA
for(l in 1:nrow(class_base)){
  if(class_base$ementa[l] == "N"){
    class_base$group[l] <- i
  } else{
    class_base$group[l] <- i
    i <- i + 1
  }
}

d_cjsg <- class_base %>% select(-ementa) %>% tidyr::spread("key", "val") %>% purrr::map_df(., ~str_trim(.x)) %>%
  dplyr::bind_cols(infos, id_page, txt_summary) %>% {
    if (!tibble::has_name(., "ementa"))
      dplyr::mutate(., ementa = NA_character_)
    else .} %>% 
  dplyr::select(id_page,
                id_decision,
                id_lawsuit,
                class_subject = classeassunto,
                district = comarca,
                court = orgao_julgador,
                dt_decision = data_julgamento,
                dt_publication = data_publicacao,
                #dt_registration = data_registro,
                rapporteur = relatora,
                summary = ementa,
                txt_summary)


readr::write_rds(d_cjsg, "data-raw_al/data_rds/d_cjsg.rds")
```

