---
title: "Tarefas_ABJ"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

* TRF para coletar

1 - TRF 1; [link](http://www.cjf.jus.br/juris/trf1/)

2 - TRF 2; [link](http://www10.trf2.jus.br/consultas/?entqr=3&lr=lang_pt&ie=UTF-8&oe=UTF-8&adv=1&ulang=&access=p&entqrm=0&wc=200&wc_mc=0&ud=1&filter=0&getfields=*&q=&client=v2_index&proxystylesheet=v2_index&site=v2_jurisprudencia&sort=date:D:S:d1&base=JP-TRF)

3 - TRF 3; [link](http://web.trf3.jus.br/base-textual)

4 - TRF 5; [link](https://www4.trf5.jus.br/Jurisprudencia/)

* TJ (Todos os estados consulta processual e de jurisprudencia)

TJSP: [consulta processual](https://esaj.tjsp.jus.br/cposg/open.do) e [jurisprudência](https://esaj.tjsp.jus.br/cjsg/consultaCompleta.do)

TJAL: [consulta processual](https://www2.tjal.jus.br/cposg5/open.do) e [jurisprudência](https://www2.tjal.jus.br/cjsg/consultaCompleta.do)

TJRJ (somente a jurisprudencia): [jurisprudência](http://www4.tjrj.jus.br/ejuris/ConsultarJurisprudencia.aspx)

TJDFT: [consulta processual](https://www.tjdft.jus.br/consultas) e [jurisprudência](https://pesquisajuris.tjdft.jus.br/IndexadorAcordaos-web/sistj?visaoId=tjdf.sistj.acordaoeletronico.buscaindexada.apresentacao.VisaoBuscaAcordao)

* VARAS (Somente consulta processual)

JFSP: [consulta processual](http://csp.jfsp.jus.br/csp/consulta/consinternet.csp) e jurisprudência

JFRJ: [consulta processual](http://procweb.jfrj.jus.br/portal/consulta/cons_procs.asp) e jurisprudência

JFAL: [consulta processual](http://www.jfal.jus.br/servicos/processos/eletronicos/creta/consulta) e jurisprudência

JFDF: [consulta processual](https://processual.trf1.jus.br/consultaProcessual/) e jurisprudência

* Diario

#### Scrappers de Jurisprudência e Consulta processual

|Tribunais|Tipo_Scraper       |Scraper_feito|Parser_feito|Obs|
|:-------:|:------------------|------------:|:----------:|:--|
|TRF-1    |Jurisprudência     |SIM          |SIM         |   |
|TRF-2    |Jurisprudência     |SIM          |SIM         |   |
|TRF-3    |Jurisprudência     |SIM          |SIM         |   |
|TRF-5    |Jurisprudência     |SIM          |SIM         |   |
|TRF-1    |Consulta Processual|SIM          |SIM         |   |
|TRF-2    |Consulta Processual|SIM          |SIM*        |Parser de movimentacao feito, porém o de infos gerais em andamento (Indisponibilidade do sistema SIAPRO no período de 19 a 23 de março)|
|TRF-3    |Consulta Processual|SIM          |SIM         |   |
|TRF-5    |Consulta Processual|SIM          |NÃO         |Parser parcial; TRF5 fora do ar (05/03)|
|TJAL     |Jurisprudência     |SIM          |SIM         |   |
|TJDFT    |Jurisprudência     |SIM          |SIM         |   |
|TJSP     |Jurisprudência     |SIM          |SIM         |   |
|TJRJ     |Jurisprudência     |SIM          |SIM         |É preciso coletar todos os docs|
|TJAL     |Consulta Processual|SIM          |SIM         |   |
|TJDFT    |Consulta Processual|SIM          |SIM         |   |
|TJSP     |Consulta Processual|SIM          |SIM         |   |
|TJRJ     |Consulta Processual|NÃO          |NÃO         |Problemas na coleta|
|JFSP     |Consulta Processual|SIM          |SIM         |   |
|JFAL     |Consulta Processual|NÃO          |NÃO         |   |
|JFRJ     |Consulta Processual|SIM          |NÃO         |   |
|JFDF     |Consulta Processual|NÃO          |NÃO         |   |

#### Algumas análises

##### 06 de Março

1. Numeros de processos em segunda instancia que você levantou separado por TJ/TRF

2. Taxa de arquivamento nos processos de segunda inst

#### Coleta dos diários

Objetivo: Construir scrapers dos diários da primeira instância.

|Tribunais|Scraper feito|Obs                                                         |
|--------:|:-----------:|-----------------------------------------------------------:|
|TJSP     |Pacote DJE   |o pacote está funcionando                                   |
|TJAL     |Pacote DJE   |o pacote está funcionando                                   |
|TJRJ     |SIM          |Passagem pelo captcha                                       |
|TJDFT    |SIM          |                                                            |
|JFSP     |SIM          |Parser realizado. Os documentos não são pdf, mas sim HTMLs  |
|JFAL     |NÃO          |Em andamento (Requisição ok, porém acesso as informaçes não)|
|JFRJ     |SIM          |                                                            |
|JFDF     |SIM          |                                                            |

#### Locais dos arquivos

|Tribunais|Tipo_Scraper       |path_RMD                                              |path_RDS|
|:-------:|:------------------|-----------------------------------------------------:|-------:|
|TRF-1    |Jurisprudência     |trfs/jurisprudencia/trf1-jurisprudencia.Rmd           |        |
|TRF-2    |Jurisprudência     |trfs/jurisprudencia/trf2-jurisprudencia.Rmd           |data-raw/rds_data/trf2_v2.rds|
|TRF-3    |Jurisprudência     |trfs/jurisprudencia/trf3-jurisprudencia.Rmd           |        |
|TRF-5    |Jurisprudência     |trfs/jurisprudencia/TRFs-jurisprudencia.Rmd           |        |
|TRF-1    |Consulta Processual|trfs/consulta_processual/TRF1/trf1-ConsProcessual.Rmd |        |
|TRF-2    |Consulta Processual|trfs/consulta_processual/TRF2/trf2-ConsProcessual.Rmd |        |
|TRF-3    |Consulta Processual|trfs/consulta_processual/TRF3/trf3-ConsProcessual.Rmd |        |
|TRF-5    |Consulta Processual|trfs/consulta_processual/TRF5/trf5-ConsProcessual.Rmd |        |
|TJAL     |Jurisprudência     |tjs/jurisprudencia/TJAL/TJAL-Juris.Rmd                |        |
|TJDFT    |Jurisprudência     |tjs/jurisprudencia/TJDFTL/jurisprudencia-TJDFT.Rmd    |        |
|TJSP     |Jurisprudência     |tjs/jurisprudencia/TJSP/TJSP-Juris.Rmd                |        |
|TJRJ     |Jurisprudência     |tjs/jurisprudencia/TJRJ/jurisprudencia-TJRJ.Rmd       |        |
|TJAL     |Consulta Processual|tjs/consulta_processual/TJAL/TJAL-ConsProcessual.Rmd  |        |
|TJDFT    |Consulta Processual|tjs/consulta_processual/TJDFT/TJDFT-ConsProcessual.Rmd|        |
|TJSP     |Consulta Processual|tjs/consulta_processual/TJSP/TJSP-ConsProcessual.Rmd  |        |
|TJRJ     |Consulta Processual|tjs/consulta_processual/TJRJ/ConsProcessual-TJRJ.Rmd  |        |
|JFSP     |Consulta Processual|jfs/JFSP/notasJFSP.Rmd                                |        |
|JFAL     |Consulta Processual|                                                      |        |
|JFRJ     |Consulta Processual|jfs/JFRJ_Selenium.R                                   |        |
|JFDF     |Consulta Processual|                                                      |        |


