---
title: "DJE-TJRJ"
output: html_notebook
---

```{r}
library(httr)
library(rvest)
library(dplyr)
library(purrr)
library(stringr)
```

```{r}
qntd_paginas <- function(caderno, date_string){
  url_qntd_paginas <- "https://www3.tjrj.jus.br/consultadje/caderno.asmx/ConsultarQuantidadePaginas"  
  query_post <- list(
    "codCaderno"=caderno,
    "dtPub"=date_string
  )
  request_qntd_pg <- httr::POST(url_qntd_paginas,
                                body = query_post,
                                httr::config(ssl_verifypeer = FALSE),
                                encode = "json")

  num_paginas <- request_qntd_pg %>% 
    httr::content() %>% 
    unlist() %>% 
    as.numeric() %>% {
      if(. == 0){
        0
      } else{
        seq(1, ., 1)
      }
    }
  
  return(num_paginas)
}
#qntd_paginas(caderno = "S", dtPub = "09/03/2018")

# eh preciso obter o _dc mas esta dificil
# url_0 <- "https://www3.tjrj.jus.br/consultadje/consultaDJE.aspx"
# 
# date_string <- "14/03/2018"
# caderno <- "A"
# pagina <- -1
# 
# query_0 <- list(
#   "dtPub"=date_string,
#   "caderno"=caderno,
#   "pagina"=pagina
#   )
# 
# request_0 <- httr::GET(url_0, query = query_0, httr::config(ssl_verifypeer = FALSE),
#                        handle = httr::handle("https://www3.tjrj.jus.br/consultadje/consultaDiario.aspx?dtPub=14/03/2018&caderno=A&pagina=-1&pesquisa=&intranet=N&_dc=1522709860256"))
# request_0$url %>% 
#   rvest::html_session(httr::config(ssl_verifypeer = FALSE)) %>% 
#   rvest::html_form()

# request_0 %>% httr::content() %>% 
#   rvest::html_nodes(xpath = '//form') %>% 
#   rvest::html_attr("action") %>% 
#   stringr::str_replace_all("^.", "") %>% 
#   stringr::str_c("https://www3.tjrj.jus.br/consultadje", .) %>% 
#   httr::POST(httr::config(ssl_verifypeer = FALSE)) %>% 
#   httr::content() %>% 
#   rvest::html_nodes(xpath = '//iframe')

obter_linkPDF <- function(date_string, caderno, pagina, dc = 1522675292694){
  
  query_1 <- list(
  "dtPub"=date_string,
  "caderno"=caderno,
  "pagina"=pagina,
  "_dc"=dc
  )
  # url_download eh um link que direciona para o link do pdf sem precisar passar pelo captcha
  url_download <- "https://www3.tjrj.jus.br/consultadje/pdf.aspx"

  request <- httr::GET(url_download, query = query_1, httr::config(ssl_verifypeer = FALSE))  
  
  return(request$url)
}

#obter_linkPDF(date_string = "09/03/2018", caderno = "S", pagina = 1, dc = 1522710519786)
# Quando o arquivo não existe volta uma url sem a query GEDID

linkPDF <- function(date_string = "09/03/2018", caderno = "S", dc = 1522710519786){
  
  paginas <- qntd_paginas(caderno = caderno, date_string = date_string)
  
  links <- purrr::map_chr(paginas, ~obter_linkPDF(date_string = date_string, caderno = caderno, pagina = .x, dc = dc))
  
  lista_links <- tibble::tibble(date_string = rep(date_string, length(links)), link = links, page = paginas)
  
  return(lista_links)
}

cadernos <- c(Judicial2instancia = "S", Judicial1instanciaCapital = "C", Judicial1instanciaInteriror = "I")
datas <- seq(as.Date("2013-01-01"), as.Date("2017-01-01"), by = 1)
tab_datas <- tibble::tibble(datas = datas) %>% 
  dplyr::mutate(dia_semana = lubridate::wday(datas, label = T)) %>% 
  tidyr::separate(datas, into = c("ano", "mes", "dia"), sep = "-") %>% 
  dplyr::mutate(datas_padrao = stringr::str_c(dia, mes, ano, sep = "/"))

coleta1_S <- purrr::map_dfr(tab_datas$datas_padrao[1:200],~linkPDF(date_string = .x, caderno = "S"))

coleta1_S$link -> vetor_link
coleta1_S -> dataframe
obter_pdf <- function(dataframe, path){
  df_filter <- dataframe %>% dplyr::mutate(flag = stringr::str_detect(link, "(default.aspx)")) %>% 
    dplyr::filter(flag == T)
  vetor_pdf <- df_filter %>% 
    select(link) %>% purrr::pluck(1)
  
}
```

