---
title: "DJE-Justica Federal da Quinta Regiao"
output: html_notebook
---

```{r}
library(httr)
library(rvest)
library(dplyr)
library(purrr)
library(RSelenium)
```

Nesta primeira tentativa, o campo mês apresenta problemas.
```{r}
url <- "https://www4.trf5.jus.br/diarioeletinternet/"

query <- list(
  "autoScroll"="",
  "frmVisao"="frmVisao",
  "frmVisao:edicao"="1",
  "frmVisao:j_id45"="Pesquisar",
  "frmVisao:meses"="", # Problema no mês
  "frmVisao:orgao"="80",
  "frmVisao:periodo"="2014",
  "javax.faces.ViewState"= httr::POST(url,httr::config(ssl_verifypeer = FALSE)) %>% 
    xml2::read_html() %>% html_node(xpath = '//*[@id="javax.faces.ViewState"]') %>% rvest::html_attr("value")
)
path <- "data-raw/"
dir.create(path, FALSE, TRUE)
path <- normalizePath(path)
file <- stringr::str_c(path, "/busca.html")
request <- httr::POST(url,body = query, 
           httr::config(ssl_verifypeer = FALSE),encode = "form",
           httr::write_disk(file, TRUE))
# Como fazer para colocar um temporizador
```

```{r DEU CERTO}
url <- "https://www4.trf5.jus.br/diarioeletinternet/paginas/consultas/consultaDiario.faces"

query <- list(
  #"AJAXREQUEST"="_viewRoot",
  "autoScroll"="",
  "frmVisao"="frmVisao",
  "frmVisao:edicao"="1",
  "frmVisao:j_id45"="Pesquisar",
  "frmVisao:meses"="02",
  "frmVisao:orgao"="80",
  "frmVisao:periodo"="2014",
  "frmPesquisa:quantidadeRegistros"="100",
  "javax.faces.ViewState"= httr::POST(url,httr::config(ssl_verifypeer = FALSE)) %>% 
    xml2::read_html() %>% html_node(xpath = '//*[@id="javax.faces.ViewState"]') %>% rvest::html_attr("value"))

path <- "data-raw/"
dir.create(path, FALSE, TRUE)
path <- normalizePath(path)
file <- stringr::str_c(path, "/busca.html")
request <- httr::POST(url,body = query, 
           httr::config(ssl_verifypeer = FALSE),encode = "form",
           httr::write_disk(file, TRUE))
```


Sendo assim, irei partir para o Selenium

```{r}
url <- "http://www4.trf5.jus.br/diarioeletinternet/"
path <- "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/dje/just_fed_quinta_regiao/data-raw/"
fprof <- makeFirefoxProfile(list(browser.download.dir = path,
                                 browser.download.folderList = 2L, 
                                 browser.download.manager.showWhenStarting = F,
                                 browser.helperApps.neverAsk.saveToDisk="text/xml",
                                 browser.tabs.remote.autostart =T,
                                 browser.tabs.remote.autostart.2 = T,
                                 browser.tabs.remote.desktopbehavior = T))
remDr <- RSelenium::rsDriver(browser = "firefox", extraCapabilities = fprof)
remDr <- remDr$client
remDr$navigate(url)

# Acessando o orgao
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmVisao:orgao"]/option[@value="80"]')
webElem$clickElement()
# Acessando a edição
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmVisao:edicao"]/option[@value="1"]')
webElem$clickElement()
# Acessando as dadas
## Ano
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmVisao:periodo"]/option[@value="2012"]')
webElem$clickElement()
## Mes
Sys.sleep(2)
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmVisao:meses"]')
webElem$clickElement()
Sys.sleep(1)
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmVisao:meses"]/option[@value="02"]')
webElem$clickElement()
# Pesquisar
webElem <- remDr$findElement(using = 'xpath', value = '//input[@id="frmVisao:j_id48"]')
webElem$clickElement()
Sys.sleep(3)
# Mudando a quantidade de registros que aparecem
webElem <- remDr$findElement(using = 'xpath', value = '//select[@id="frmPesquisa:quantidadeRegistros"]/option[@value="100"]')
webElem$clickElement()
# Obtendo os download
## Obtendo o html para saber quantas iteração serao necessarias
page_source <- remDr$getPageSource()
node <- page_source %>% purrr::pluck(1) %>% xml2::read_html()
tables <- node %>% html_table(fill = T) 
for(i in 1:length(tables)){
  if(ncol(tables[[i]])==5){
    tabela <- tables[[i]]
  }
}
### ultima_pag <- node %>% rvest::html_node(xpath = '//span[@id="frmPesquisa:pageCountTeste"]') %>% rvest::html_text() %>% stringr::str_extract("[0-9]+")

### Extraido o objeto ultima_pag, podemos iterar para percorrer as paginas
webElems <- remDr$findElements(using = 'xpath', value = '//center/a[@title="Arquivo"]')
for(i in 1:length(webElems)){
  webElems[[i]]$clickElement()
  Sys.sleep(5)
}
```
```{r}
library(tidyverse)

get_state <- function(r) {
  r %>% 
    httr::content("text") %>% 
    xml2::read_html() %>% 
    rvest::html_node(xpath = "//input[@id='javax.faces.ViewState']") %>% 
    rvest::html_attr("value")
}

get_jid <- function(r) {
  r %>% 
    httr::content("text") %>% 
    xml2::read_html() %>% 
    rvest::html_node(xpath = "//input[@type='submit']") %>% 
    rvest::html_attr("id")
}

pag_inicial <- function(orgao = "80", edicao = "1", periodo = "2017", meses = "02") {
  u0 <- "https://www4.trf5.jus.br/diarioeletinternet/index.jsp"
  u <- "https://www4.trf5.jus.br/diarioeletinternet/paginas/consultas/consultaDiario.faces"
  r <- httr::GET(u0, httr::config(ssl_verifypeer = FALSE))
  
  l_stj <- list('frmVisao:orgao' = orgao,
                'frmVisao:edicao' = edicao,
                'frmVisao:periodo' = periodo,
                'frmVisao:meses' = "",
                'frmVisao' = 'frmVisao',
                'autoScroll' = '',
                'javax.faces.ViewState' = get_state(r))
  
  # request inicial para carregar os meses
  jid <- get_jid(r)
  l_stj[[jid]] <- jid
  l_stj[["AJAXREQUEST"]] <- "_viewRoot"
  httr::POST(u, body = l_stj, httr::config(ssl_verifypeer = FALSE), 
             encode = "form")
  
  # request final para pegar a primeira pagina
  jid <- get_jid(r)
  l_stj[[jid]] <- "Pesquisar"
  l_stj[["AJAXREQUEST"]] <- NULL
  l_stj[["frmVisao:meses"]] <- meses
  l_stj[['frmPesquisa:quantidadeRegistros']] <- '100'
  r_post_first <- httr::POST(u, body = l_stj, 
                             httr::config(ssl_verifypeer = FALSE),
                             encode = "form")
  
  r
}


paginar <- function(r_post) {
  u <- "https://www4.trf5.jus.br/diarioeletinternet/paginas/consultas/consultaDiario.faces"
  l_stj <- list('AJAXREQUEST' = '_viewRoot',
                'frmPesquisa:pagina' = 1,
                'frmPesquisa:quantidadeRegistros' = '10',
                'frmPesquisa' = 'frmPesquisa',
                'autoScroll' = '',
                'javax.faces.ViewState' = get_state(r_post))
  jid <- get_jid(r_post)
  l_stj[[jid]] <- jid
  
  r_post_pag <- httr::POST(u, body = l_stj, 
                           httr::config(ssl_verifypeer = FALSE),
                           encode = "form")
  
  l_stj <- list('frmPesquisa:pagina' = 1,
                'frmPesquisa:quantidadeRegistros' = '100',
                'frmPesquisa' = 'frmPesquisa',
                'autoScroll' = '',
                'javax.faces.ViewState' = get_state(r_post))

  jid <- get_jid(r_post)
  l_stj[[jid]] <- "Pesquisar"

  r_post_pag <- httr::POST(u, body = l_stj,
                           httr::config(ssl_verifypeer = FALSE),
                           encode = "form")
  
  r_post_pag
}


inicial <- pag_inicial()
pag <- paginar(inicial)

scrapr::html_view(pag)
```

