---
title: "TRF5-ConsProcessual"
output: html_notebook
---

```{r}
#library(RSelenium)
library(rvest)
library(dplyr)
library(httr)
library(decryptr)
library(data.table)
```

```{r}
# exemplos para construcao do scrapper
## 00014068420174050000
## 200683000106242
## 200405000360589
trf5_processos <- readr::read_rds("/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/trfs/jurisprudencia/data-raw/rds_data/trf5.rds") %>% 
  dplyr::select(inteiro_teor) %>% tidyr::drop_na() %>% purrr::pluck(1) %>% unique() 


path <- "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/trfs/consulta_processual/TRF5/data-raw/"

obter_ConsTRF5 <- function(query, path){
  url <- "http://www.trf5.jus.br/cp/cp.do"
  query_GET <- list("filtro"=query,
                   "tipo" = "xmlproc",
                   "navigation" = "Netscape",
                   "vinculados"="true",
                   "ordenacao" = "D",
                   "tipoproc" = "T",
                   "ordenacao+cpf"="D")
  proc <- stringr::str_replace_all(query, "[[:punct:]]", "") %>% 
    stringr::str_c(.,".html")
  dir.create(path, FALSE, TRUE)
  path <- normalizePath(path)
  file <- stringr::str_c(path, "/")
  PathFile <- stringr::str_c(file, proc)
  
  httr::POST(url, query = query_GET, 
             httr::config(ssl_verifypeer = FALSE),
             write_disk(PathFile, overwrite = T)) 
}
purrr::map2(trf5_processos, path, ~obter_ConsTRF5(.x,.y))
```

```{r}
file <- dir(path = "data-raw/", full.names = T)

# Obtendo os nodes
node <- file[1] %>% read_html()

# Movimentacao
parse_movimentacao <- function(node, file){
  print(file)
  mov_node <- node %>%
    html_table(fill = T) %>% 
    .[6:length(.)]

  movimentacao <- mov_node %>% 
    purrr::map_dfc(~select_(.x , .x %>% colnames() %>% dplyr::last())) %>% 
    data.table::transpose() %>% {
      if(ncol(.) == 3){
        magrittr::set_names(., c("data", "mov", "detalhe"))
        } else if (ncol(.) == 2){
          magrittr::set_names(., c("data", "mov"))
          }
      } %>% 
    mutate(data = stringr::str_replace_all(data, "[E-e]m", ""),
           data = stringr::str_trim(data),
           file = file) %>% 
    dplyr::group_by(file) %>% 
    tidyr::separate(data, c("data", "hora"), sep = " ") %>% 
    tidyr::nest(.key = "movimentacao")

  return(movimentacao)
}
movimentacao <- parse_movimentacao(node, file[4])
movimentacao$movimentacao
# Informacoes gerais
# proc <- node %>% 
#   html_node(xpath = '/html/body/p[2]') %>%
#   html_text() %>% 
#   stringr::str_replace_all("[^0-9]", "")

# info_node <- node %>%
#   html_table(fill = T) %>% 
#   .[1:5]

# Informacoes gerais 26/04/2018

#TABELA 1
parse_info_proc <- function(node){
  proc <- node %>% 
    html_node(xpath = '/html/body/p[2]') %>%
    html_text() %>% 
    stringr::str_replace_all("[^0-9]", "")
  node %>% 
    html_nodes(xpath = '//table[1]//tr/td') %>%
    purrr::map_chr(., ~html_text(.x)) %>% 
    stringr::str_trim() %>%
    stringr::str_to_lower() %>%
    .[!stringr::str_detect(.,"(autuado)|(inquérito \\(inq)|(ação penal)|(apelação criminal)|(agravo \\()")] %>%
    tibble(key = .) %>% 
    tidyr::separate(key, c("key", "val"), sep = ":") %>% 
    mutate(key = stringr::str_to_lower(key),
           key = stringr::str_replace_all(key, "[[:punct:]]",""),
           key = abjutils::rm_accent(key),
           key = stringr::str_replace_all(key, " +", "_"),
           processo = proc) %>% 
    tidyr::spread(key, val)
}
parse_info_proc(node)

# TABELA 3
parse_partes <- function(node){
  node %>% 
    html_nodes(xpath = '//table[3]//tr/td') %>%
    purrr::map_chr(., ~html_text(.x)) %>% 
    stringr::str_trim() %>% 
    tibble(key = .) %>% 
    tibble::rownames_to_column(var = "flag") %>% 
    mutate(flag = sjmisc::is_even(as.numeric(flag))) %>% {
      key <- filter(., flag == FALSE)
      val <- filter(., flag != FALSE)
      bind_cols(key,val)
      } %>% select(-dplyr::matches("(flag)")) %>% {
        if (ncol(.)==2){
          magrittr::set_names(., c("key", "val"))
          }
        } %>% 
    mutate(key = stringr::str_to_lower(key),
           key = stringr::str_replace_all(key, "[[:punct:]]",""),
           key = abjutils::rm_accent(key),
           key = stringr::str_replace_all(key, " +", "_"),
           val = stringr::str_replace_all(val, ":|\\t", ""))%>% 
    group_by(key) %>% #Como lidar com dados duplicados
    summarise(val = glue::collapse(val, sep = "@@@")) %>%
    ungroup() %>%
    tidyr::spread(key, val) %>% 
    tidyr::nest(.key = "Partes")
}
parse_partes(node)

# TABELA 4
parse_peticoes <- function(node){
 node %>% 
    html_nodes(xpath = '//table[4]//tr/td') %>%
    purrr::map_chr(., ~html_text(.x)) %>% 
    stringr::str_trim() %>% tibble(key = .) %>% 
    tidyr::nest(.key = "Peticoes")
}
parse_peticoes(node)  

# Juntando tudo

parse_trf5 <- function(file){
  node <- file %>% read_html()
  verificador <- node %>% html_nodes(xpath = '//*[@title="Nova Consulta"]') %>% html_text()
  
  if(purrr::is_empty(verificador)){
      movimentacao <- parse_movimentacao(node, file)
    info_proc <- parse_info_proc(node)
    partes <- parse_partes(node)
    peticoes <- parse_peticoes(node)
    tab <- dplyr::bind_cols(info_proc,
                            movimentacao,
                            partes,
                            peticoes)
  } else {
    tab <- tibble(file = file, result = "error")
  }
  return(tab)
}
purrr::map_dfr(file,~parse_trf5(.x))

# --------------------------------------------------------------#

info_1 <- info_node %>% purrr::pluck(1) %>% select_(., colnames(.) %>% dplyr::first()) %>% 
  magrittr::set_names("key") %>% 
  tidyr::separate(key, c("key", "val"), sep = ":")

for (i in 1:nrow(info_1)){
  if(stringr::str_detect(info_1$val[i], "[A-z]|[0-9]")==F & is.na(info_1$val[i])==F){
    info_1$val[i] <- NA
  }
}

info_1$val[1] <- info_1$key[1]
info_1$key[1] <- "classe"

info_1 <- info_1 %>%
  mutate(key = stringr::str_to_lower(key),
         key = stringr::str_replace_all(key, "[[:punct:]]",""),
         key = abjutils::rm_accent(key),
         key = stringr::str_replace_all(key, " +", "_")) %>% 
  tidyr::spread(key, val)

info_2 <- info_node %>% purrr::pluck(3) %>% 
  magrittr::set_names(c("key", "val")) %>% 
  mutate(key = stringr::str_to_lower(key),
         key = stringr::str_replace_all(key, "[[:punct:]]",""),
         key = abjutils::rm_accent(key),
         key = stringr::str_replace_all(key, " +", "_"),
         val = stringr::str_replace_all(val, ":|\\t", "")) %>% 
  tidyr::spread(key, val)

parse_table <- dplyr::bind_cols(info_1, info_2, movimentacao)


```

