---
title: "TJDFT-ConsProcessual"
author: "Nathan Giachetta"
output: html_document
---

```{r}
library(httr)
library(rvest)
library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
```


```{r}
d_cjsg <- readr::read_rds("/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/jurisprudencia/TJDFT/data-raw/rds_files/data.rds")

processos <- d_cjsg %>% 
  tidyr::separate(col = "classe_do_processo", c("classe_inquerito", "processo"), 
                  sep = " - \\(", remove = F) %>% 
  tidyr::separate(col = "processo", c("processo", "res_cnj", "segredo_justica"), sep = "- ") %>% 
  select(processo) %>% 
  sjmisc::remove_empty_rows() %>% 
  purrr::pluck(1) %>% 
  stringr::str_trim()
```

```{r}
obter_proc <- function(query, path){
  url <- "https://cache-internet.tjdft.jus.br/cgi-bin/tjcgi1?NXTPGM=plhtml01&MGWLPN=SERVIDOR1&submit=ok&SELECAO=1&CHAVE=&ORIGEM=INTER"

  query_GET <-list(
    "NXTPGM" = "plhtml02",
    "MGWLPN" = "SERVIDOR1",
    "SELECAO" = "1",
    "ORIGEM" = "INTER",
    "COMAND" = "Pesquisar",
    "CHAVE" = query
    )
  
  proc <- stringr::str_replace_all(query, "[[:punct:]]", "") %>% 
  stringr::str_c(.,".html")
  dir.create(path, FALSE, TRUE)
  path <- normalizePath(path)
  file <- stringr::str_c(path, "/")
  PathFile <- stringr::str_c(file, proc)
  httr::GET(url, query = query_GET,
            httr::config(ssl_verifypeer = FALSE),
            write_disk(PathFile, overwrite = T))
}

path <- "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/consulta_processual/TJDFT/data-raw/d_cposg"

purrr::map(processos , ~obter_proc(.x, path))

files_cposg <- dir("/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/consulta_processual/TJDFT/data-raw/d_cposg/", full.names = TRUE)
```

## Parseando os dados

```{r}
# Parsando a tabela de movimentacao

# Existem alguns html que nao possuem formatacao padrao
# Esta funcao verifica se a tabela de movimentacao exite ou nao.
# Caso nao exista eh preciso clicar no link correto para acessa-la
tab_vazia <- function(node){
  teste <- node %>% html_node(xpath = '//table[@cellspacing="0"]')
  is_empty(teste)
}

parse_mov <- function(files_cposg){
  # Lendo html
  node <- xml2::read_html(files_cposg)
  # Verifica se a pagina html tem o padrao esperado
  if (tab_vazia(node) == TRUE){
    link <- node %>% html_nodes(xpath = '//li/a') %>% html_attr('href')
    inq_detect <- stringr::str_detect(link ,"CDNUPROC=INQ|CDNUPROC=[0-9]+INQ")
    inq <- link[inq_detect]
    node <- read_html(inq)
  }
  # Obtendo a ultima tabela
  movimentacao <- node %>% 
    rvest::html_table(fill=T, header = T) %>% 
    dplyr::last()
  # Retirando espacos desnecessarios
  movimentacao[,1] <- map_chr(movimentacao[1:nrow(movimentacao),1], stringr::str_trim)
  movimentacao[,2] <- map_chr(movimentacao[1:nrow(movimentacao),2], stringr::str_trim)
  # Preenchendo celulas vazias
  for(i in 1:nrow(movimentacao)){
    if(nchar(movimentacao[i,1]) == 0 & nchar(movimentacao[i,2])== 0){
      movimentacao[i,1] <- NA
      movimentacao[i,2] <- NA
    } else if (nchar(movimentacao[i,1]) == 0){
      movimentacao[i,1] <- movimentacao[i-1,1]
    }
  }
  # Transformando o data.frame de movimentacao em nest e depois as datas em nest
  movimentacao <- movimentacao %>% 
    tidyr::drop_na() %>% 
    magrittr::set_names(c("data", "mov")) %>%
    group_by(data) %>% 
    tidyr::nest(.key = "mov") %>% 
    mutate(file = files_cposg) %>% 
    ungroup() %>% 
    group_by(file) %>% 
    tidyr::nest(.key = "data")
  
  return(movimentacao)
}

mov_tab <- map(files_cposg, parse_mov) %>% 
  dplyr::bind_rows()

readr::write_rds(mov_tab, "data-raw/movimentacao/mov_tab.rds")
```

```{r}
# Parseando informaçoes gerais

parse_dados_proc <- function(files_cposg){
  node <- xml2::read_html(files_cposg)
  
  if (tab_vazia(node) == TRUE){
    link <- node %>% html_nodes(xpath = '//li/a') %>% html_attr('href')
    inq_detect <- stringr::str_detect(link ,"CDNUPROC=INQ|CDNUPROC=[0-9]+INQ")
    inq <- link[inq_detect]
    node <- read_html(inq)
  }
  
  dados_proc <- node %>% 
    html_table(fill = T) %>% 
    dplyr::first() %>% 
    magrittr::set_names(c("key", "val")) %>% 
    mutate(key = stringr::str_replace_all(key,":","") %>% 
             abjutils::rm_accent(),
           key = stringr::str_trim(key),
           key = stringr::str_replace_all(key, " +", "_"),
           key = stringr::str_to_lower(key),
           val = stringr::str_trim(val),
           val = ifelse(stringr::str_length(val) == 0, yes = NA, no = val)) %>% 
    tidyr::drop_na(val) %>%
        t()
  
  colnames(dados_proc) <- dados_proc[1,]
  
  dados_proc <- as.data.frame(dados_proc)
  
  dados_proc <- dados_proc[-1,] 
  
  dados_proc <- dados_proc %>% 
    #select(-contains("decisao"), -contains("notas_taq"), - contains("andamento")) %>% 
    tidyr::nest(.key = "dados_processo") %>% 
    mutate(file = files_cposg[1])
  
  return(dados_proc)
}

dados_proc_tab <- map(files_cposg, parse_dados_proc) %>%  dplyr::bind_rows()

readr::write_rds(dados_proc_tab, "data-raw/dados_proc/dados_proc_tab.rds")
```

