---
title: "DJE-Justica Federal da Terceira Regiao"
output: html_notebook
---
```{r message=F, warning=FALSE}
library(httr)
library(rvest)
library(dplyr)
library(purrr)
```

```{r}
request_POST_GET <- function(method = "POST", url, query = NULL, file){
  if (is.null(query) == T & method == "POST"){
    request <- httr::POST(url, 
           httr::config(ssl_verifypeer = FALSE),
           httr::write_disk(file, TRUE))
  }else if(is.null(query) == F & method == "POST"){
    request <- httr::POST(url, body = query, 
           httr::config(ssl_verifypeer = FALSE),
           httr::write_disk(file, TRUE))    
  }else if (is.null(query) == T & method == "GET"){
    request <- httr::GET(url, 
           httr::config(ssl_verifypeer = FALSE),
           httr::write_disk(file, TRUE))
  }else {
    request <- httr::GET(url, query = query, 
           httr::config(ssl_verifypeer = FALSE),
           httr::write_disk(file, TRUE))  
  }

  return(request)
}

change_date_format <- function(seqDateStringr, sep = "/"){
  seqDateStringr %>% lubridate::as_date() %>% lubridate::ymd() %>% {
  dia <- lubridate::day(.) %>% as.character()
  mes <- lubridate::month(.) %>% as.character()
  ano <- lubridate::year(.) %>% as.character()
  tibble(dia = dia, mes = mes, ano = ano)
} %>% 
  dplyr::mutate(dia = stringr::str_c("0", dia) %>% 
                  ifelse(stringr::str_length(.) == 3, stringr::str_replace(., "0", ""), .),
                mes = stringr::str_c("0", mes) %>% 
                  ifelse(stringr::str_length(.) == 3, stringr::str_replace(., "0", ""), .),
                data = stringr::str_c(dia, mes, ano, sep = sep)) %>% 
    select(data) %>% purrr::pluck(1)
}


# Obtendo a primeira pagina
obter_dje_jfsp <- function(orgao = 2, tipoPublicacao = 1, dataInicialYMD = "2013-01-01", dataFinalYMD = "2016-12-31", path = "data-raw/data-raw_html/"){
  
  dates <- as.character(seq(as.Date(dataInicialYMD), as.Date(dataFinalYMD), by = "day"))
  dates <- change_date_format(dates, sep = "/")
  
  url <- "http://web.trf3.jus.br/diario/Consulta/ResultadoPesquisa/"  
  
  url_1 <- stringr::str_c(url, "1")
  
  queries_by_date <- list()
  for(i in 1:length(dates)){
    queries_by_date[[i]] <- list(
    "FiltroPesquisaPublicacao.CodigoOrgao"=orgao,	# 2 eh SJSP
    "FiltroPesquisaPublicacao.CodigoTipoPublicacao"=tipoPublicacao, # Vai de 1 a 9
    "FiltroPesquisaPublicacao.CodigoUnidade"="",
    "FiltroPesquisaPublicacao.DataInicial"=dates[i],
    "FiltroPesquisaPublicacao.DataFinal"=dates[i],
    "FiltroPesquisaPublicacao.DocumentosPagina"="100",
    "FiltroPesquisaPublicacao.IdSerie"="",	
    "FiltroPesquisaPublicacao.NomeLocalidade"="",
    "FiltroPesquisaPublicacao.NumeroOab"="",
    "FiltroPesquisaPublicacao.NumeroProcesso"=""
    )
  }
  
  dir.create(path, FALSE, TRUE)
  path <- normalizePath(path)
  file <- stringr::str_c(path, "/page1.html")
  
  request <- request_POST_GET(method = "POST",
                              url = url_1,
                              query = queries_by_date,
                              file = file)
  
  node <- request %>% xml2::read_html()

  total_pag <- node %>% html_node(xpath = '//form/label') %>% html_text() %>%
    stringr::str_extract("[0-9]+$") %>% as.numeric()
  
  qnt_percorrer <- 2:ceiling(total_pag/100)

  urls <- list()
  files <- list()
  for(i in 1:length(qnt_percorrer)){
    urls[[i]] <- stringr::str_c(url, qnt_percorrer[i])
    files[[i]] <- stringr::str_c(path, "/page", qnt_percorrer[i], ".html")
  }
  
  purrr::map2(urls, files,~request_POST_GET(method = "GET", .x, file = .y, query = query))
}

obter_dje_jfsp()



files_path <- dir(path = "data-raw/", pattern = "page", full.names = T)


parse_file <- function(file){
  node_file <- file %>% xml2::read_html()

  tabela <- node_file %>% html_table(fill = T) %>% purrr::pluck(1) %>% {
    if(ncol(.) == 6){
      magrittr::set_names(.,c("vazio", "data_disponibilizacao", "orgao", "unidade", "tipo_publicacao", "doc_publ"))
    }
  } %>% 
  dplyr::select(-doc_publ, -vazio)
  link_diario <- tibble(link_diario = node_file %>%
           html_nodes(xpath = '//td[@class="alinhamento"]/a') %>%
           html_attr("href") %>%
           stringr::str_c("http://web.trf3.jus.br",.))
  tabela <- dplyr::bind_cols(tabela, link_diario) %>% dplyr::mutate(file = file)
  return(tabela)
}

tabela <- map_dfr(files_path, ~parse_file(.x))
```