---
title: "TJAL-ConsProcessual"
author: "Nathan Giachetta"
output: html_document
---

# TJAL: Consulta Processual

```{r}
library(rvest)
library(dplyr)
library(stringr)
library(httr)
library(purrr)
```

```{r}
d_cjsg <- readr::read_rds("/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/jurisprudencia/TJAL/data-raw_al/data_rds/d_cjsg.rds")

processos <- unique(d_cjsg$id_lawsuit) %>%
  na.omit() 
path <- "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/consulta_processual/TJAL/data-raw_AL/d_cposg/"

obter_proc <-function(query, path){
  url <- "https://www2.tjal.jus.br/cposg5/search.do"
  
  # Preenchendo o formulário
  query_GET <- list(`conversationId`="",
                    `cbPesquisa`="NUMPROC",
                    `tipoNuProcesso`="UNIFICADO",
                    `dePesquisaNuUnificado` = query,
                    `uuidCaptcha`="",
                    `chNmCompleto`="true",
                    `pbEnviar`="Pesquisar")

  proc <- stringr::str_replace_all(query, "[[:punct:]]", "") %>% 
    stringr::str_c(.,".html")
  dir.create(path, FALSE, TRUE)
  path <- normalizePath(path)
  file <- stringr::str_c(path, "/")
  PathFile <- stringr::str_c(file, proc)
  httr::GET(url, query = query_GET,
            httr::config(ssl_verifypeer = FALSE),
            write_disk(PathFile, overwrite = T))
}

purrr::map(processos , ~obter_proc(.x, path))
```

```{r}
# Parseando CPOSG
files_cposg <- dir("/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/consulta_processual/TJAL/data-raw_AL/d_cposg/", full.names = TRUE)

node <- xml2::read_html(files_cposg[3], enconding = "UTF-8")

# MOVIMENTACAO

parse_mov <- function(node){
 mov <- node %>% rvest::html_nodes('#tabelaTodasMovimentacoes')

 mov <- mov %>% 
   html_nodes(xpath = '//tr[@class="fundoClaro"]|//tr[@class="fundoEscuro"]') %>%
   html_text() %>%
   stringr::str_trim() %>%
   stringr::str_replace("\\n", "quebralinhaaqui") %>%
   as_tibble()  %>%
   tidyr::separate(value, into= c("data", "movimento"), sep = "(quebralinhaaqui)") %>%
   tidyr::drop_na()
 
  mov <- mov[stringr::str_detect(mov$data, "[0-9]"),] 
  
  mov <- mov %>% tidyr::nest(.key = movimentacao)
  
  return(mov)
}

# DADOS DO PROCESSO

parse_data_prc <- function(node){
  
  prc <- node %>%
  rvest::html_nodes('.secaoFormBody') %>%
  rvest::html_table(fill = T) %>% 
  dplyr::last() %>% 
  magrittr::set_names(c("key", "val", "delete")) %>% 
  tidyr::drop_na(val) %>% 
  select(-delete) %>% 
  mutate(key = stringr::str_trim(key),
         key = stringr::str_replace_all(key, "[[:punct:]]", ""),
         key = stringr::str_replace_all(key, " +", "_"),
         key = stringr::str_to_lower(key),
         key = abjutils::rm_accent(key)) %>% 
  tidyr::spread(key, val) #%>% 
  #tidyr::unite(ultima_carga, V1, ultima_carga, sep = " \n")
  
  prc <- prc %>% tidyr::nest(.key = dados_processo)
  
  return(prc)
}

# PARTES

parse_partes <- function(node){
  
  partes <- node %>% 
  rvest::html_node('#tablePartesPrincipais') %>%
  rvest::html_table() %>% 
  magrittr::set_names(c("key", "val")) %>% 
  mutate(key = stringr::str_trim(key),
         key = stringr::str_replace_all(key, "[[:punct:]]", ""),
         key = stringr::str_replace_all(key, " +", "_"),
         key = stringr::str_to_lower(key),
         key = abjutils::rm_accent(key)) %>% 
  tidyr::spread(key, val) #%>% 
  #tidyr::separate(reu, c("reu", "advogado"), sep = "(Advogado)")
  
  partes <- partes %>% tidyr::nest(.key = partes)
  
  return(partes)
}

# JULGAMENTO

parse_julgamento <- function(node){
  
  julgamento <- node %>% rvest::html_nodes(xpath ='(//td[@class="esajCelulaConteudoServico"]//table)[last()-1]') %>%
    rvest::html_table(fill = T) %>% 
    dplyr::bind_rows() %>% 
    magrittr::set_names(c("data", "situacao_julgamento", "decisao")) 
  
  julgamento <- julgamento %>% tidyr::nest(.key = julgamento)
  
  return(julgamento)
}
```

```{r}
node <- xml2::read_html(files_cposg[1], enconding = "UTF-8")

data <- tibble()
for (i in 1:length(files_cposg)){
  node <- xml2::read_html(files_cposg[i], enconding = "UTF-8")
  
  proc <- parse_data_prc(node)
  partes <- parse_partes(node)
  movimentacao <- parse_mov(node)
  julgamento <- parse_julgamento(node)
  
  data <- dplyr::bind_cols(as_tibble(files_cposg[i]), proc, partes, movimentacao, julgamento) %>% 
    dplyr::bind_rows(data)
  
}

readr::write_rds(data, path = "/home/nathang/Documentos/Scripts and Documents/ESTAGIO_ABJ/ABJ/tjs/consulta_processual/TJAL/data-raw_AL/cposg_rds_AL/cposg.rds")
```

