---
title: "TRF2-Jurisprudencia"
output: html_notebook
---

```{r}
library(dplyr)
library(httr)
library(rvest)
library(stringr)
library(tidyr)
```

# Função para obter os dados

```{r}
build_query_trf2 <- function(q = "", classe = "INQUÉRITO POLICIAL", daterange = c("01-01-2003", "04-04-2018"), path = getwd()){
  url <- "http://www10.trf2.jus.br/consultas/"  
  
  if(classe != ""){
    classe <- stringr::str_c("DescrRecursoFinal:",classe)  
  }
  
  if(daterange != ""){
    daterange <- lubridate::dmy(daterange) %>% lubridate::ymd() %>% as.character()
    daterange <- stringr::str_c(daterange[1], "..", daterange[2])
    daterange <- stringr::str_c("inmeta:DataDecisao:daterange:",daterange)  
  }
  
  query <- list(
    "output"="xml_no_dtd",
    "proxystylesheet"="v2_index",
    "getfields"="*",
    "entqr"=3,
    "lr"="lang_pt",
    "ie"="UTF-8",
    "oe"="UTF-8",
    "requiredfields"=classe,
    "sort"="date:D:S:d1",
    "entsp"="a",
    "adv"=1,
    "base"="JP-TRF",
    "ulang"="",
    "access"="p",
    "entqrm"=0,
    "wc"=200,
    "wc_mc"=0,
    "ud"=1,
    "client"="v2_index",
    "filter"=0,
    "as_q"=daterange,
    "q"=q,
    "start"=0,
    "site"="v2_jurisprudencia"
  )

  dir.create(path, FALSE, TRUE)
  path <- normalizePath(path)
  file <- stringr::str_c(path, "/page1.html")

  request <- httr::GET(url, query = query, httr::config(ssl_verifypeer = FALSE),
                       httr::write_disk(file, overwrite = T))

  node <- httr::content(request, as = "parsed")

  ultima_pagina <- node %>% 
    rvest::html_nodes(xpath = '//a[@class="pagination-link no_mobile"]') %>%
    rvest::html_attr('href') %>%
    stringr::str_extract("(start=)[0-9]+") %>%
    stringr::str_extract("[0-9]+") %>% 
    as.numeric() %>%
    sort(decreasing = F) %>%
    dplyr::last()
  # Caso o html tenha apenas uma pagina o objeto ultima_pagina
  # retornara NA

  # iterador para obter todas as paginas
  if(is.na(ultima_pagina)==F){
    vetor_paginas <- seq(0, ultima_pagina, 10)
    for (i in 1:length(vetor_paginas)){
      query$start <- vetor_paginas[i]
      path <- normalizePath(path)
      file <- stringr::str_c(path, "/page", i, ".html")
      request <- httr::GET(url, query = query,
                           httr::config(ssl_verifypeer = FALSE),
                           httr::write_disk(file, TRUE))
      Sys.sleep(1)
    }  
  }
} 

#build_query_trf2(q = "", daterange = "", path = "data-raw/TRF2/busca_v3/")

# obter_paginas <- function(request){
#   ultima_pagina <- request %>% 
#     httr::content(as = "text") %>% 
#     xml2::read_html() %>% 
#     rvest::html_nodes(xpath = '//span[@class="pagination-control"]/a') %>% 
#     rvest::html_attr('href') %>% 
#     stringr::str_extract("(start=)[0-9]+") %>%
#     stringr::str_extract("[0-9]+") %>% 
#     as.numeric() %>% 
#     sort(decreasing = F) %>% 
#     dplyr::last()
#   paginas <- seq(10, ultima_pagina, 10) 
#   
#   paginas
# }
# 
# paginas <- obter_paginas(request)
```

# Funções para parsear

```{r Parsing}
files <- dir("data-raw/TRF2/busca_v3/", pattern = "page", full.names = T)

# Ementa_versao 1
obter_ementa_v1 <- function(node){
  xpath_1 <- '//li[@class="g"]'
  node_pag <- node %>% rvest::html_nodes(xpath = xpath_1)
  ementas <- purrr::map(node_pag, ~rvest::html_text(rvest::html_nodes(.x, '.text_ementa'))) %>% 
    purrr::map_chr(., ~paste0(.x, collapse = " "))
  xpath_2 <- '//div[@class="doc-text"]/text()'
  l <- 1
  for(i in 1:length(ementas)){
    node_ <- node_pag %>% rvest::html_nodes( xpath = xpath_2) %>% rvest::html_text()
    while(nchar(ementas[i]) == 0){
      ementas[i] <- node_ %>% purrr::pluck(l)
      l <- l + 1
    }
  }
  return(tibble::tibble(ementas))
}

# Ementa_versao 2
obter_ementa_v2 <- function(node){
  xpath_1 <- '//li[@class="g"]'
  node_pag <- node %>% rvest::html_nodes(xpath = xpath_1)
  ementas <- purrr::map(node_pag, ~rvest::html_text(rvest::html_nodes(.x, '.text_ementa'))) %>% 
    purrr::map_chr(., ~paste0(.x, collapse = " "))
  return(tibble::tibble(ementas))
}

obter_outra_info <- function(node){
  classe <- node %>% rvest::html_nodes(xpath = '//span[@class="recurso"]') %>% rvest::html_text() %>% .[seq(1, length(.),2)] %>% stringr::str_replace(".*:", "") %>% stringr::str_trim()

  orgao <- node %>% rvest::html_nodes(xpath = '//span[@class="recurso"]') %>% rvest::html_text() %>% .[seq(2, length(.),2)] %>% stringr::str_replace(".*:", "") %>% stringr::str_trim()

  datas_relator <- node%>% rvest::html_nodes(xpath = '//div[@class="data-relator"]') %>% rvest::html_text()# precisa de reparo
  
  num_processo <- node %>% html_nodes('.number_link') %>% rvest::html_text(trim = T)
  
  tipo_doc <- node %>% rvest::html_nodes(xpath = '//span[@title="Ementas"]|//span[@title="Decisões"]|//span[@title="Inteiro Teor"]|//span[@class="img_base img_decisao"]') %>%
    html_text()
  
  tabela <- tibble(num_processo = num_processo, classe = classe, orgao_julgador = orgao, datas_relator = datas_relator, tipo_documento = tipo_doc)
  
  return(tabela)
}

wrapup_info <- function(node){
  ementa_v1 <- obter_ementa_v1(node)
  ementa_v2 <- obter_ementa_v2(node)
  infos <- obter_outra_info(node)
  
  tabela <- dplyr::bind_cols(infos, ementa_v2, ementa_v1)
  return(tabela)
}

nodes <- purrr::map(files, ~.x %>%  xml2::read_html())
trf2 <- purrr::map_dfr(nodes, ~wrapup_info(.x))

trf2 <- trf2 %>% 
  dplyr::mutate(dataDecisao = stringr::str_extract(datas_relator, "(Data de decisão)[0-9][0-9]\\/[0-9][0-9]\\/[0-9][0-9][0-9][0-9]") %>% 
           stringr::str_extract("[^Data de decisão].*"),
         dataDisponib = stringr::str_extract(datas_relator, "(Data de disponibilização)[0-9][0-9]\\/[0-9][0-9]\\/[0-9][0-9][0-9][0-9]") %>% 
           stringr::str_extract("[^Data de disponibilização].*"),
         relator = stringr::str_extract(datas_relator, "(Relator).*") %>% 
           stringr::str_extract("[^Relator].*")) %>% 
  dplyr::select(-datas_relator)

readr::write_rds(trf2, "data-raw/rds_data/trf2_v2.rds")
```

Errata:

Atualização da base, incluindo coluna que especifica se o documento é um Ementa, Inteiro Teor ou Decisão
Processos duplucados 

E - Ementa, I - iNTEIRO TEOR, D- Decisão
